init python:
    achievement_data = {
        "ACH_MOUSEKETEER": {
            "name": "Members Only",
            "description": "",
            "chapter": "1",
            "image": "achievement_icons\ACH_MOUSEKETEER.png",
            "image_gray": "achievement_icons\ACH_MOUSEKETEER_gray.png",
        },
        "ACH_SMILE": {
            "name": "That Damned Smile.",
            "description": "Get your cousin to flash her Pearly Whites.",
            "chapter": "1",
            "image": "achievement_icons\ACH_SMILE.png",
            "image_gray": "achievement_icons\ACH_SMILE_gray.png",
        },
        "ACH_BOYCRY": {
            "name": "The Boy Who Cried Nice House",
            "description": "Lie to Tabitha about liking your room after already getting caught lying to her.",
            "chapter": "1",
            "image": "achievement_icons\ACH_BOYCRY.png",
            "image_gray": "achievement_icons\ACH_BOYCRY_gray.png",
        },
        "ACH_EXPECTATIONS": {
            "name": "What were you expecting?",
            "description": "Pet Frou-frou in Episode 1 after being warned against it.",
            "chapter": "1",
            "image": "achievement_icons\ACH_EXPECTATIONS.png",
            "image_gray": "achievement_icons\ACH_EXPECTATIONS_gray.png",
        },
        "ACH_URBAN": {
            "name": "Urban Explorer",
            "description": "Explore every room of the estate before going to town in Episode 1.",
            "chapter": "1",
            "image": "achievement_icons\ACH_URBAN.png",
            "image_gray": "achievement_icons\ACH_URBAN_gray.png",
        },
        "ACH_PATZERO": {
            "name": "Patient Zero",
            "description": "",
            "chapter": "1",
            "image": "achievement_icons\ACH_PATZERO.png",
            "image_gray": "achievement_icons\ACH_PATZERO_gray.png",
        },
        "ACH_PBJ": {
            "name": "Cooking by the book.",
            "description": "Follow the recipe.",
            "chapter": "1",
            "image": "achievement_icons\ACH_PBJ.png",
            "image_gray": "achievement_icons\ACH_PBJ_gray.png",
        },
        "ACH_PETDOG": {
            "name": "Can You Pet the Dog?",
            "description": "You can pet the dog in Scarlet Hollow.",
            "chapter": "1",
            "image": "achievement_icons\ACH_PETDOG.png",
            "image_gray": "achievement_icons\ACH_PETDOG_gray.png",
        },
        "ACH_RIPGRETCH": {
            "name": "Old Yeller",
            "description": "",
            "chapter": "1",
            "image": "achievement_icons\ACH_RIPGRETCH.png",
            "image_gray": "achievement_icons\ACH_RIPGRETCH_gray.png",
        },
        "ACH_DUKERIP": {
            "name": "Poor Trigger Discipline",
            "description": "",
            "chapter": "1",
            "image": "achievement_icons\ACH_DUKERIP.png",
            "image_gray": "achievement_icons\ACH_DUKERIP_gray.png",
        },
        "ACH_LOSDOS": {
            "name": "Porqué no los Dos?",
            "description": "Use a trait to get out of a sticky situation in Episode 1.",
            "chapter": "1",
            "image": "achievement_icons\ACH_LOSDOS.png",
            "image_gray": "achievement_icons\ACH_LOSDOS_gray.png",
        },
        "ACH_PB1": {
            "name": "Mx North Carolina",
            "description": "Finish Episode 1 with Powerful Build as one of your traits.",
            "chapter": "1",
            "image": "achievement_icons\ACH_PB1.png",
            "image_gray": "achievement_icons\ACH_PB1_gray.png",
        },
        "ACH_MYST1": {
            "name": "Enoby Dark'ness Dementia Raven Way",
            "description": "Finish Episode 1 with Mystical as one of your traits.",
            "chapter": "1",
            "image": "achievement_icons\ACH_MYST1.png",
            "image_gray": "achievement_icons\ACH_MYST1_gray.png",
        },
        "ACH_TTA1": {
            "name": "Pasta Puppeteer",
            "description": "Finish Episode 1 with Talk to Animals as one of your traits.",
            "chapter": "1",
            "image": "achievement_icons\ACH_TTA1.png",
            "image_gray": "achievement_icons\ACH_TTA1_gray.png",
        },
        "ACH_BOOK1": {
            "name": "The Ravenous Bug",
            "description": "Finish Episode 1 with Book Smart as one of your traits.",
            "chapter": "1",
            "image": "achievement_icons\ACH_BOOK1.png",
            "image_gray": "achievement_icons\ACH_BOOK1_gray.png",
        },
        "ACH_KEEN1": {
            "name": "Mail Time",
            "description": "Finish Episode 1 with Keen Eye as one of your traits.",
            "chapter": "1",
            "image": "achievement_icons\ACH_KEEN1.png",
            "image_gray": "achievement_icons\ACH_KEEN1_gray.png",
        },
        "ACH_STREET1": {
            "name": "Candy From a Baby",
            "description": "Finish Episode 1 with Street Smart as one of your traits.",
            "chapter": "1",
            "image": "achievement_icons\ACH_STREET1.png",
            "image_gray": "achievement_icons\ACH_STREET1_gray.png",
        },
        "ACH_HOT1": {
            "name": "Bell Pepper",
            "description": "Finish Episode 1 with Hot as one of your traits.",
            "chapter": "1",
            "image": "achievement_icons\ACH_HOT1.png",
            "image_gray": "achievement_icons\ACH_HOT1_gray.png",
        },
        "ACH_SLUMBER": {
            "name": "Slumber Party!",
            "description": "",
            "chapter": "1",
            "image": "achievement_icons\ACH_SLUMBER.png",
            "image_gray": "achievement_icons\ACH_SLUMBER_gray.png",
        },
        "ACH_ESTATE1": {
            "name": "Good Cousin",
            "description": "",
            "chapter": "1",
            "image": "achievement_icons\ACH_ESTATE1.png",
            "image_gray": "achievement_icons\ACH_ESTATE1_gray.png",
        },
        "ACH_PB2": {
            "name": "Mx America",
            "description": "Finish Episode 2 with Powerful Build as one of your traits.",
            "chapter": "2",
            "image": "achievement_icons\ACH_PB2.png",
            "image_gray": "achievement_icons\ACH_PB2_gray.png",
        },
        "ACH_MYST2": {
            "name": "Sand-Hater",
            "description": "Finish Episode 2 with Mystical as one of your traits.",
            "chapter": "2",
            "image": "achievement_icons\ACH_MYST2.png",
            "image_gray": "achievement_icons\ACH_MYST2_gray.png",
        },
        "ACH_KEEN2": {
            "name": "French Inspector",
            "description": "Finish Episode 2 with Keen Eye as one of your traits.",
            "chapter": "2",
            "image": "achievement_icons\ACH_KEEN2.png",
            "image_gray": "achievement_icons\ACH_KEEN2_gray.png",
        },
        "ACH_STREET2": {
            "name": "Stealing Your Grandma's Credit Card",
            "description": "Finish Episode 2 with Street Smart as one of your traits.",
            "chapter": "2",
            "image": "achievement_icons\ACH_STREET2.png",
            "image_gray": "achievement_icons\ACH_STREET2_gray.png",
        },
        "ACH_BOOK2": {
            "name": "Whimsical Tree Adventure",
            "description": "Finish Episode 2 with Book Smart as one of your traits.",
            "chapter": "2",
            "image": "achievement_icons\ACH_BOOK2.png",
            "image_gray": "achievement_icons\ACH_BOOK2_gray.png",
        },
        "ACH_HOT2": {
            "name": "Poblano",
            "description": "Finish Episode 2 with Hot as one of your traits.",
            "chapter": "2",
            "image": "achievement_icons\ACH_HOT2.png",
            "image_gray": "achievement_icons\ACH_HOT2_gray.png",
        },
        "ACH_TTA2": {
            "name": "Jane Goodall",
            "description": "Finish Episode 2 with Talk to Animals as one of your traits.",
            "chapter": "2",
            "image": "achievement_icons\ACH_TTA2.png",
            "image_gray": "achievement_icons\ACH_TTA2_gray.png",
        },
        "ACH_NOMANLEFT": {
            "name": "No Man Left Behind",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_NOMANLEFT.png",
            "image_gray": "achievement_icons\ACH_NOMANLEFT_gray.png",
        },
        "ACH_CUTTINGLOSS": {
            "name": "Cutting Your Losses",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_CUTTINGLOSS.png",
            "image_gray": "achievement_icons\ACH_CUTTINGLOSS_gray.png",
        },
        "ACH_BABYSITTER": {
            "name": "Pro Babysitter",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_BABYSITTER.png",
            "image_gray": "achievement_icons\ACH_BABYSITTER_gray.png",
        },
        "ACH_SNITCH": {
            "name": "Ronnie the Rat",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_SNITCH.png",
            "image_gray": "achievement_icons\ACH_SNITCH_gray.png",
        },
        "ACH_NOFRIENDS": {
            "name": "I Didn't Come Here to Make Friends",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_NOFRIENDS.png",
            "image_gray": "achievement_icons\ACH_NOFRIENDS_gray.png",
        },
        "ACH_GRETCHENREGARDS": {
            "name": "Gretchen Sends Her Regards",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_GRETCHENREGARDS.png",
            "image_gray": "achievement_icons\ACH_GRETCHENREGARDS_gray.png",
        },
        "ACH_EVILTRIUMPH": {
            "name": "Evil Has Triumphed",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_EVILTRIUMPH.png",
            "image_gray": "achievement_icons\ACH_EVILTRIUMPH_gray.png",
        },
        "ACH_LION": {
            "name": "I (Don't) Want to Believe",
            "description": "Get Stella to Believe in Mountain Lions.",
            "chapter": "2",
            "image": "achievement_icons\ACH_LION.png",
            "image_gray": "achievement_icons\ACH_LION_gray.png",
        },
        "ACH_JUSTUS": {
            "name": "Just the Two of Us",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_JUSTUS.png",
            "image_gray": "achievement_icons\ACH_JUSTUS_gray.png",
        },
        "ACH_RIDEKANEEKA": {
            "name": "Mystery Machine",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_RIDEKANEEKA.png",
            "image_gray": "achievement_icons\ACH_RIDEKANEEKA_gray.png",
        },
        "ACH_WALKSTELLA": {
            "name": "Into the Woods... Again",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_WALKSTELLA.png",
            "image_gray": "achievement_icons\ACH_WALKSTELLA_gray.png",
        },
        "ACH_NOSYNANCY": {
            "name": "Nosy Nancy",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_NOSYNANCY.png",
            "image_gray": "achievement_icons\ACH_NOSYNANCY_gray.png",
        },
        "ACH_COURTESYCALL": {
            "name": "Courtesy Call",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_COURTESYCALL.png",
            "image_gray": "achievement_icons\ACH_COURTESYCALL_gray.png",
        },
        "ACH_MINION": {
            "name": "Minion",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_MINION.png",
            "image_gray": "achievement_icons\ACH_MINION_gray.png",
        },
        "ACH_OOTL": {
            "name": "Out of the Loop",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_OOTL.png",
            "image_gray": "achievement_icons\ACH_OOTL_gray.png",
        },
        "ACH_STEALTHRUN": {
            "name": "Stealth Run",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_STEALTHRUN.png",
            "image_gray": "achievement_icons\ACH_STEALTHRUN_gray.png",
        },
        "ACH_MANAGER": {
            "name": "I Want to Talk to Your Manager",
            "description": "Visit Tabitha's office during a clandestine investigation on Tuesday.",
            "chapter": "2",
            "image": "achievement_icons\ACH_MANAGER.png",
            "image_gray": "achievement_icons\ACH_MANAGER_gray.png",
        },
        "ACH_COFFEE": {
            "name": "Coffee Date",
            "description": "Get coffee with Avery.",
            "chapter": "2",
            "image": "achievement_icons\ACH_COFFEE.png",
            "image_gray": "achievement_icons\ACH_COFFEE_gray.png",
        },
        "ACH_CONFIDANT": {
            "name": "Confidant",
            "description": "Tell Avery the truth about last night.",
            "chapter": "2",
            "image": "achievement_icons\ACH_CONFIDANT.png",
            "image_gray": "achievement_icons\ACH_CONFIDANT_gray.png",
        },
        "ACH_KEEPSECRET": {
            "name": "Alright Then, Keep Your Secrets",
            "description": "Don't tell Avery the truth about last night.",
            "chapter": "2",
            "image": "achievement_icons\ACH_KEEPSECRET.png",
            "image_gray": "achievement_icons\ACH_KEEPSECRET_gray.png",
        },
        "ACH_BROWSING": {
            "name": "Just Browsing",
            "description": "Visit the general store without stealing anything.",
            "chapter": "2",
            "image": "achievement_icons\ACH_BROWSING.png",
            "image_gray": "achievement_icons\ACH_BROWSING_gray.png",
        },
        "ACH_STICKYFINGERS": {
            "name": "Sticky Fingers",
            "description": "Steal from the general store.",
            "chapter": "2",
            "image": "achievement_icons\ACH_STICKYFINGERS.png",
            "image_gray": "achievement_icons\ACH_STICKYFINGERS_gray.png",
        },
        "ACH_HYGGE": {
            "name": "Hygge",
            "description": "Make a cozy nest for a fuzzy friend.",
            "chapter": "1",
            "image": "achievement_icons\ACH_HYGGE.png",
            "image_gray": "achievement_icons\ACH_HYGGE_gray.png",
        },
        "ACH_combo": {
            "name": "Fusion",
            "description": "Take a menu option that requires two traits.",
            "chapter": "1",
            "image": "achievement_icons\ACH_combo.png",
            "image_gray": "achievement_icons\ACH_combo_gray.png",
        },
        "ACH_oops": {
            "name": "Ya blew it",
            "description": "Get a bad outcome while you had a trait that could have avoided it.",
            "chapter": "1",
            "image": "achievement_icons\ACH_oops.png",
            "image_gray": "achievement_icons\ACH_oops_gray.png",
        },
        "ACH_kington": {
            "name": "Master Codebreaker",
            "description": "Break into the forbidden wings of the Estate.",
            "chapter": "1",
            "image": "achievement_icons\ACH_kington.png",
            "image_gray": "achievement_icons\ACH_kington_gray.png",
        },
        "ACH_boomer": {
            "name": "Father, how do I click the book?",
            "description": "Leave the library in Episode 2 without reading any books.",
            "chapter": "2",
            "image": "achievement_icons\ACH_boomer.png",
            "image_gray": "achievement_icons\ACH_boomer_gray.png",
        },
        "ACH_phantom": {
            "name": "Prying Pandora",
            "description": "Pull back the veil.",
            "chapter": "2",
            "image": "achievement_icons\ACH_phantom.png",
            "image_gray": "achievement_icons\ACH_phantom_gray.png",
        },
        "ACH_squelch": {
            "name": "Squelch",
            "description": "",
            "chapter": "1",
            "image": "achievement_icons\ACH_squelch.png",
            "image_gray": "achievement_icons\ACH_squelch_gray.png",
        },
        "ACH_goku": {
            "name": "Imma deck you in the schnoz!",
            "description": "In a single playthrough with Powerful Build, choose violence at least twice.",
            "chapter": "2",
            "image": "achievement_icons\ACH_goku.png",
            "image_gray": "achievement_icons\ACH_goku_gray.png",
        },
        "ACH_LOREMASTER": {
            "name": "Loremaster",
            "description": "Read every entry in all ~four~ books in the library!",
            "chapter": "2",
            "image": "achievement_icons\ACH_LOREMASTER.png",
            "image_gray": "achievement_icons\ACH_LOREMASTER_gray.png",
        },
        "ACH_DITCHLING": {
            "name": "Ditchling",
            "description": "",
            "chapter": "1",
            "image": "achievement_icons\ACH_DITCHLING.png",
            "image_gray": "achievement_icons\ACH_DITCHLING_gray.png",
        },
        "ACH_TOMMYKNOCKER": {
            "name": "Tommyknocker",
            "description": "",
            "chapter": "2",
            "image": "achievement_icons\ACH_TOMMYKNOCKER.png",
            "image_gray": "achievement_icons\ACH_TOMMYKNOCKER_gray.png",
        },
        "ACH_PLAYFIELD": {
            "name": "Playing the Field",
            "description": "Keeping your options open.",
            "chapter": "3",
            "image": "achievement_icons\ACH_PLAYFIELD.png",
            "image_gray": "achievement_icons\ACH_PLAYFIELD_gray.png",
        },
        "ACH_PAC": {
            "name": "Generous Campaign Contribution",
            "description": "Donate to a local politician.",
            "chapter": "3",
            "image": "achievement_icons\ACH_PAC.png",
            "image_gray": "achievement_icons\ACH_PAC_gray.png",
        },
        "ACH_DIRTY": {
            "name": "Unclean",
            "description": "End Episode 3 without having showered.",
            "chapter": "3",
            "image": "achievement_icons\ACH_DIRTY.png",
            "image_gray": "achievement_icons\ACH_DIRTY_gray.png",
        },
        "ACH_SHOWER": {
            "name": "Wash away your sins",
            "description": "Shower.",
            "chapter": "3",
            "image": "achievement_icons\ACH_SHOWER.png",
            "image_gray": "achievement_icons\ACH_SHOWER_gray.png",
        },
        "ACH_DRIL": {
            "name": "I’m not owned! I’m not owned!",
            "description": "Resist your new nickname.",
            "chapter": "2",
            "image": "achievement_icons\ACH_DRIL.png",
            "image_gray": "achievement_icons\ACH_DRIL_gray.png",
        },
        "ACH_PINKERTON": {
            "name": "Pinkerton",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_PINKERTON.png",
            "image_gray": "achievement_icons\ACH_PINKERTON_gray.png",
        },
        "ACH_PROBLEMATICFAV": {
            "name": "I can fix her!",
            "description": "Spend some quality time with Tabitha.",
            "chapter": "3",
            "image": "achievement_icons\ACH_PROBLEMATICFAV.png",
            "image_gray": "achievement_icons\ACH_PROBLEMATICFAV_gray.png",
        },
        "ACH_HOSPITALITY": {
            "name": "Southern Hospitality",
            "description": "Spend some quality time with Stella.",
            "chapter": "3",
            "image": "achievement_icons\ACH_HOSPITALITY.png",
            "image_gray": "achievement_icons\ACH_HOSPITALITY_gray.png",
        },
        "ACH_RIVER": {
            "name": "Family Burdens",
            "description": "Spend some quality time with Kaneeka.",
            "chapter": "3",
            "image": "achievement_icons\ACH_RIVER.png",
            "image_gray": "achievement_icons\ACH_RIVER_gray.png",
        },
        "ACH_FEMALEGAZE": {
            "name": "I'm Looking Respectfully.",
            "description": "Spend some quality time with Oscar.",
            "chapter": "3",
            "image": "achievement_icons\ACH_FEMALEGAZE.png",
            "image_gray": "achievement_icons\ACH_FEMALEGAZE_gray.png",
        },
        "ACH_EAGLES": {
            "name": "New Kid in Town",
            "description": "Spend some quality time with Avery.",
            "chapter": "3",
            "image": "achievement_icons\ACH_EAGLES.png",
            "image_gray": "achievement_icons\ACH_EAGLES_gray.png",
        },
        "ACH_FRED": {
            "name": "Let's See Who This Really Is",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_FRED.png",
            "image_gray": "achievement_icons\ACH_FRED_gray.png",
        },
        "ACH_THUNDERROAD": {
            "name": "Thunder Road.",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_THUNDERROAD.png",
            "image_gray": "achievement_icons\ACH_THUNDERROAD_gray.png",
        },
        "ACH_GUMSHOE": {
            "name": "Mr X.",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_GUMSHOE.png",
            "image_gray": "achievement_icons\ACH_GUMSHOE_gray.png",
        },
        "ACH_SINS": {
            "name": "The Sins of the Father...",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_SINS.png",
            "image_gray": "achievement_icons\ACH_SINS_gray.png",
        },
        "ACH_SINSDEAL": {
            "name": "Are To Be Laid Upon the Children",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_SINSDEAL.png",
            "image_gray": "achievement_icons\ACH_SINSDEAL_gray.png",
        },
        "ACH_SINSBREAK": {
            "name": "Shall Not Be Visited Upon the Son",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_SINSBREAK.png",
            "image_gray": "achievement_icons\ACH_SINSBREAK_gray.png",
        },
        "ACH_ILLUSION": {
            "name": "The Illusion of Choice",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_ILLUSION.png",
            "image_gray": "achievement_icons\ACH_ILLUSION_gray.png",
        },
        "ACH_PHOENIX": {
            "name": "The Haunted Turnabout",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_PHOENIX.png",
            "image_gray": "achievement_icons\ACH_PHOENIX_gray.png",
        },
        "ACH_POLTERGEIST": {
            "name": "This House is Clean",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_POLTERGEIST.png",
            "image_gray": "achievement_icons\ACH_POLTERGEIST_gray.png",
        },
        "ACH_RESONANT": {
            "name": "Resonant",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_RESONANT.png",
            "image_gray": "achievement_icons\ACH_RESONANT_gray.png",
        },
        "ACH_TTA3": {
            "name": "Teen Talker",
            "description": "Finish Episode 3 with Talk to Animals.",
            "chapter": "3",
            "image": "achievement_icons\ACH_TTA3.png",
            "image_gray": "achievement_icons\ACH_TTA3_gray.png",
        },
        "ACH_PB3": {
            "name": "Mx World",
            "description": "Finish Episode 3 with Powerful Build.",
            "chapter": "3",
            "image": "achievement_icons\ACH_PB3.png",
            "image_gray": "achievement_icons\ACH_PB3_gray.png",
        },
        "ACH_MYST3": {
            "name": "Card Master",
            "description": "Finish Episode 3 with Mystical.",
            "chapter": "3",
            "image": "achievement_icons\ACH_MYST3.png",
            "image_gray": "achievement_icons\ACH_MYST3_gray.png",
        },
        "ACH_HOT3": {
            "name": "Jalapeño",
            "description": "Finish Episode 3 with Hot.",
            "chapter": "3",
            "image": "achievement_icons\ACH_HOT3.png",
            "image_gray": "achievement_icons\ACH_HOT3_gray.png",
        },
        "ACH_BOOK3": {
            "name": "A Supernatural Love Affair",
            "description": "Finish Episode 3 with Book Smart.",
            "chapter": "3",
            "image": "achievement_icons\ACH_BOOK3.png",
            "image_gray": "achievement_icons\ACH_BOOK3_gray.png",
        },
        "ACH_STREET3": {
            "name": "This is a Stick-Up!",
            "description": "Finish Episode 3 with Street Smart.",
            "chapter": "3",
            "image": "achievement_icons\ACH_STREET3.png",
            "image_gray": "achievement_icons\ACH_STREET3_gray.png",
        },
        "ACH_KEEN3": {
            "name": "Detective Arriving on the Scene",
            "description": "Finish Episode 3 with Keen Eye.",
            "chapter": "3",
            "image": "achievement_icons\ACH_KEEN3.png",
            "image_gray": "achievement_icons\ACH_KEEN3_gray.png",
        },
        "ACH_HOTMONSTER": {
            "name": "Monster Lover",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_HOTMONSTER.png",
            "image_gray": "achievement_icons\ACH_HOTMONSTER_gray.png",
        },
        "ACH_GHOSTMAX": {
            "name": "The Gang's All Here",
            "description": "Go ghost hunting with the maximum number of participants.",
            "chapter": "3",
            "image": "achievement_icons\ACH_GHOSTMAX.png",
            "image_gray": "achievement_icons\ACH_GHOSTMAX_gray.png",
        },
        "ACH_GHOSTMIN": {
            "name": "Tight-Knit Social Circle",
            "description": "Go ghost hunting with the minimum number of participants.",
            "chapter": "3",
            "image": "achievement_icons\ACH_GHOSTMIN.png",
            "image_gray": "achievement_icons\ACH_GHOSTMIN_gray.png",
        },
        "ACH_SEANCE": {
            "name": "Seance",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_SEANCE.png",
            "image_gray": "achievement_icons\ACH_SEANCE_gray.png",
        },
        "ACH_GETOUT": {
            "name": "Get Out of My Head!",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_GETOUT.png",
            "image_gray": "achievement_icons\ACH_GETOUT_gray.png",
        },
        "ACH_TURN": {
            "name": "Not an Ambi-Turner.",
            "description": "Just keep turning.",
            "chapter": "3",
            "image": "achievement_icons\ACH_TURN.png",
            "image_gray": "achievement_icons\ACH_TURN_gray.png",
        },
        "ACH_FLIGHT": {
            "name": "Cat and Mouse",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_FLIGHT.png",
            "image_gray": "achievement_icons\ACH_FLIGHT_gray.png",
        },
        "ACH_KAIOKEN": {
            "name": "TIMES THREE!",
            "description": "Choose violence at least three times.",
            "chapter": "3",
            "image": "achievement_icons\ACH_KAIOKEN.png",
            "image_gray": "achievement_icons\ACH_KAIOKEN_gray.png",
        },
        "ACH_LIFELINE": {
            "name": "Lifeline",
            "description": "",
            "chapter": "3",
            "image": "achievement_icons\ACH_LIFELINE.png",
            "image_gray": "achievement_icons\ACH_LIFELINE_gray.png",
        },
        "ACH_KEEN4": {
            "name": "Louisiana Hunch",
            "description": "Finish Episode 4 with Keen Eye.",
            "chapter": "4",
            "image": "achievement_icons\ACH_KEEN4.png",
            "image_gray": "achievement_icons\ACH_KEEN4_gray.png",
        },
        "ACH_PB4": {
            "name": "Mx Galaxy",
            "description": "Finish Episode 4 with Powerful Build.",
            "chapter": "4",
            "image": "achievement_icons\ACH_PB4.png",
            "image_gray": "achievement_icons\ACH_PB4_gray.png",
        },
        "ACH_STICKBUG": {
            "name": "Get Stick Bugged",
            "description": "Communicate with the Elusive North Carolinian Phasmid.",
            "chapter": "4",
            "image": "achievement_icons\ACH_STICKBUG.png",
            "image_gray": "achievement_icons\ACH_STICKBUG_gray.png",
        },
        "ACH_STELLA_TABITHA": {
            "name": "I Never Forgot About You",
            "description": "Mend a Broken Relationship.",
            "chapter": "4",
            "image": "achievement_icons\ACH_STELLA_TABITHA.png",
            "image_gray": "achievement_icons\ACH_STELLA_TABITHA_gray.png",
        },
        "ACH_STELLA_FOUND": {
            "name": "At the Edge of Everything...",
            "description": "Find out what happened to Stella.",
            "chapter": "4",
            "image": "achievement_icons\ACH_STELLA_FOUND.png",
            "image_gray": "achievement_icons\ACH_STELLA_FOUND_gray.png",
        },
        "ACH_STELLA_GONE": {
            "name": "Where in the World is Stella Richmond?",
            "description": "Finish Episode 4 without finding Stella.",
            "chapter": "4",
            "image": "achievement_icons\ACH_STELLA_GONE.png",
            "image_gray": "achievement_icons\ACH_STELLA_GONE_gray.png",
        },
        "ACH_OSCARMANCE": {
            "name": "Dream Daddy",
            "description": "Start Oscar's romance.",
            "chapter": "4",
            "image": "achievement_icons\ACH_OSCARMANCE.png",
            "image_gray": "achievement_icons\ACH_OSCARMANCE_gray.png",
        },
        "ACH_ROMANCE": {
            "name": "This is a Dating Sim, Right?",
            "description": "Start a romance.",
            "chapter": "4",
            "image": "achievement_icons\ACH_ROMANCE.png",
            "image_gray": "achievement_icons\ACH_ROMANCE_gray.png",
        },
        "ACH_STELLAMANCE": {
            "name": "Tear Down the Wall",
            "description": "Start Stella's romance.",
            "chapter": "4",
            "image": "achievement_icons\ACH_STELLAMANCE.png",
            "image_gray": "achievement_icons\ACH_STELLAMANCE_gray.png",
        },
        "ACH_KANEEKAMANCE": {
            "name": "You can't start a fire...",
            "description": "Start Kaneeka's Romance",
            "chapter": "4",
            "image": "achievement_icons\ACH_KANEEKAMANCE.png",
            "image_gray": "achievement_icons\ACH_KANEEKAMANCE_gray.png",
        },
        "ACH_REESEMANCE": {
            "name": "Monster Lover II",
            "description": "",
            "chapter": "4",
            "image": "achievement_icons\ACH_REESEMANCE.png",
            "image_gray": "achievement_icons\ACH_REESEMANCE_gray.png",
        },
        "ACH_LIBRARY4": {
            "name": "Library Card",
            "description": "Visit Oscar in the Library in Episode 4.",
            "chapter": "4",
            "image": "achievement_icons\ACH_LIBRARY4.png",
            "image_gray": "achievement_icons\ACH_LIBRARY4_gray.png",
        },
        "ACH_MAXWELL4": {
            "name": "At Least It's (Probably) Not Haunted",
            "description": "Visit the Old Maxwell Place in Episode 4.",
            "chapter": "4",
            "image": "achievement_icons\ACH_MAXWELL4.png",
            "image_gray": "achievement_icons\ACH_MAXWELL4_gray.png",
        },
        "ACH_DINER4": {
            "name": "What's the Buzz?",
            "description": "Visit the Diner in Episode 4.",
            "chapter": "4",
            "image": "achievement_icons\ACH_DINER4.png",
            "image_gray": "achievement_icons\ACH_DINER4_gray.png",
        },
        "ACH_MINES": {
            "name": "Picket Line",
            "description": "Visit the Mines in Episode 4.",
            "chapter": "4",
            "image": "achievement_icons\ACH_MINES.png",
            "image_gray": "achievement_icons\ACH_MINES_gray.png",
        },
        "ACH_CHURCH4": {
            "name": "The Smallest Church in Scarlet Hollow",
            "description": "Visit the Church in Episode 4.",
            "chapter": "4",
            "image": "achievement_icons\ACH_CHURCH4.png",
            "image_gray": "achievement_icons\ACH_CHURCH4_gray.png",
        },
        "ACH_STILL": {
            "name": "Still Life",
            "description": "Visit Stella's on Thursday morning.",
            "chapter": "4",
            "image": "achievement_icons\ACH_STILL.png",
            "image_gray": "achievement_icons\ACH_STILL_gray.png",
        },
        "ACH_POLICE4": {
            "name": "Why Won't They Just Do Their Jobs?",
            "description": "Visit the Police in Episode 4.",
            "chapter": "4",
            "image": "achievement_icons\ACH_POLICE4.png",
            "image_gray": "achievement_icons\ACH_POLICE4_gray.png",
        },
        "ACH_HACKER": {
            "name": "Hackerman",
            "description": "Snoop on Stella's computer in Episode 4. Find everything!",
            "chapter": "4",
            "image": "achievement_icons\ACH_HACKER.png",
            "image_gray": "achievement_icons\ACH_HACKER_gray.png",
        },
        "ACH_GOAT": {
            "name": "Dustin Quest",
            "description": "",
            "chapter": "4",
            "image": "achievement_icons\ACH_GOAT.png",
            "image_gray": "achievement_icons\ACH_GOAT_gray.png",
        },
        "ACH_TEA": {
            "name": "Tea Reading",
            "description": "Drink the tea. It's good for you.",
            "chapter": "4",
            "image": "achievement_icons\ACH_TEA.png",
            "image_gray": "achievement_icons\ACH_TEA_gray.png",
        },
        "ACH_TEASPILL": {
            "name": "Spill the Tea",
            "description": "",
            "chapter": "4",
            "image": "achievement_icons\ACH_TEASPILL.png",
            "image_gray": "achievement_icons\ACH_TEASPILL_gray.png",
        },
        "ACH_DUSTINBETRAY": {
            "name": "Friendship Ended with Dresser Rat",
            "description": "Now anybody else is my best friend.",
            "chapter": "4",
            "image": "achievement_icons\ACH_DUSTINBETRAY.png",
            "image_gray": "achievement_icons\ACH_DUSTINBETRAY_gray.png",
        },
        "ACH_BASEMENT4": {
            "name": "The Excavation of Oscar's Basement",
            "description": "Return to the Basement.",
            "chapter": "4",
            "image": "achievement_icons\ACH_BASEMENT4.png",
            "image_gray": "achievement_icons\ACH_BASEMENT4_gray.png",
        },
        "ACH_SNITCHSNITCH": {
            "name": "Rodriguez the Rat",
            "description": "Walk in on a meeting.",
            "chapter": "4",
            "image": "achievement_icons\ACH_SNITCHSNITCH.png",
            "image_gray": "achievement_icons\ACH_SNITCHSNITCH_gray.png",
        },
        "ACH_HARRISONSTOP": {
            "name": "Saving the Family Business",
            "description": "Stop someone from joining the strike.",
            "chapter": "4",
            "image": "achievement_icons\ACH_HARRISONSTOP.png",
            "image_gray": "achievement_icons\ACH_HARRISONSTOP_gray.png",
        },
        "ACH_OBEDIENT": {
            "name": "Obedient",
            "description": "",
            "chapter": "4",
            "image": "achievement_icons\ACH_OBEDIENT.png",
            "image_gray": "achievement_icons\ACH_OBEDIENT_gray.png",
        },
        "ACH_REESE_DEAD": {
            "name": "Cousin Bonding Time",
            "description": "",
            "chapter": "4",
            "image": "achievement_icons\ACH_REESE_DEAD.png",
            "image_gray": "achievement_icons\ACH_REESE_DEAD_gray.png",
        },
        "ACH_STATUS_QUO": {
            "name": "Keeping the status quo",
            "description": "",
            "chapter": "4",
            "image": "achievement_icons\ACH_STATUS_QUO.png",
            "image_gray": "achievement_icons\ACH_STATUS_QUO_gray.png",
        },
        "ACH_MATRICIDE": {
            "name": "Matricide",
            "description": "",
            "chapter": "4",
            "image": "achievement_icons\ACH_MATRICIDE.png",
            "image_gray": "achievement_icons\ACH_MATRICIDE_gray.png",
        },
        "ACH_BEASTMASTER": {
            "name": "Tame the Beast",
            "description": "",
            "chapter": "4",
            "image": "achievement_icons\ACH_BEASTMASTER.png",
            "image_gray": "achievement_icons\ACH_BEASTMASTER_gray.png",
        },
        "ACH_WHOAMI": {
            "name": "Time to Whip Out the Old String and Corkboard",
            "description": "",
            "chapter": "4",
            "image": "achievement_icons\ACH_WHOAMI.png",
            "image_gray": "achievement_icons\ACH_WHOAMI_gray.png",
        },
        "ACH_ASMR": {
            "name": "Antagonistic Doctor Roleplay (ASMR)",
            "description": "Get a check-up.",
            "chapter": "4",
            "image": "achievement_icons\ACH_ASMR.png",
            "image_gray": "achievement_icons\ACH_ASMR_gray.png",
        },
        "ACH_BOOK4": {
            "name": "Of Mice and Men",
            "description": "Finish Episode 4 with Book Smart.",
            "chapter": "4",
            "image": "achievement_icons\ACH_BOOK4.png",
            "image_gray": "achievement_icons\ACH_BOOK4_gray.png",
        },
        "ACH_STREET4": {
            "name": "Good ol' Fashion Train Robbery",
            "description": "Finish Episode 4 with Street Smart.",
            "chapter": "4",
            "image": "achievement_icons\ACH_STREET4.png",
            "image_gray": "achievement_icons\ACH_STREET4_gray.png",
        },
        "ACH_MYST4": {
            "name": "Wish Maker",
            "description": "Finish Episode 4 with Mystical.",
            "chapter": "4",
            "image": "achievement_icons\ACH_MYST4.png",
            "image_gray": "achievement_icons\ACH_MYST4_gray.png",
        },
        "ACH_TTA4": {
            "name": "Creature Consolation",
            "description": "Finish Episode 4 with Talk to Animals.",
            "chapter": "4",
            "image": "achievement_icons\ACH_TTA4.png",
            "image_gray": "achievement_icons\ACH_TTA4_gray.png",
        },
        "ACH_HOT4": {
            "name": "Cayenne",
            "description": "Finish Episode 4 with Hot.",
            "chapter": "4",
            "image": "achievement_icons\ACH_HOT4.png",
            "image_gray": "achievement_icons\ACH_HOT4_gray.png",
        },
        "ACH_ICE_CREAM": {
            "name": "Ice Cream Social",
            "description": "Unwind with your family after a long day.",
            "chapter": "4",
            "image": "achievement_icons\ACH_ICE_CREAM.png",
            "image_gray": "achievement_icons\ACH_ICE_CREAM_gray.png",
        },
        "ACH_ARTIST": {
            "name": "The Artist",
            "description": "",
            "chapter": "4",
            "image": "achievement_icons\ACH_ARTIST.png",
            "image_gray": "achievement_icons\ACH_ARTIST_gray.png",
        },
        "ACH_HARDCORE1": {
            "name": "No",
            "description": "Finish Episode 1 in Hardcore Mode.",
            "chapter": "1",
            "image": "achievement_icons\ACH_HARDCORE1.png",
            "image_gray": "achievement_icons\ACH_HARDCORE1_gray.png",
        },
        "ACH_HARDCORE2": {
            "name": "No no",
            "description": "Finish Episode 2 in Hardcore Mode.",
            "chapter": "2",
            "image": "achievement_icons\ACH_HARDCORE2.png",
            "image_gray": "achievement_icons\ACH_HARDCORE2_gray.png",
        },
        "ACH_HARDCORE3": {
            "name": "No no no",
            "description": "Finish Episode 3 in Hardcore Mode.",
            "chapter": "3",
            "image": "achievement_icons\ACH_HARDCORE3.png",
            "image_gray": "achievement_icons\ACH_HARDCORE3_gray.png",
        },
        "ACH_HARDCORE4": {
            "name": "No no no no",
            "description": "Finish Episode 4 in Hardcore Mode.",
            "chapter": "4",
            "image": "achievement_icons\ACH_HARDCORE4.png",
            "image_gray": "achievement_icons\ACH_HARDCORE4_gray.png",
        },
        "ACH_MONDAY_STORE": {
            "name": "The Holler",
            "description": "Chat with Kaneeka at the general store early Monday afternoon.",
            "chapter": "1",
            "image": "achievement_icons\ACH_MONDAY_STORE.png",
            "image_gray": "achievement_icons\ACH_MONDAY_STORE_gray.png",
        },
        "ACH_MONDAY_LIBRARY": {
            "name": "History Lesson",
            "description": "Have a chat at the library early Monday afternoon.",
            "chapter": "1",
            "image": "achievement_icons\ACH_MONDAY_LIBRARY.png",
            "image_gray": "achievement_icons\ACH_MONDAY_LIBRARY_gray.png",
        },
        "ACH_MONDAY_DUKE": {
            "name": "Cracking Open a Cold One",
            "description": "Spend some quality time with Ol' Duke.",
            "chapter": "1",
            "image": "achievement_icons\ACH_MONDAY_DUKE.png",
            "image_gray": "achievement_icons\ACH_MONDAY_DUKE_gray.png",
        },
        "ACH_MONDAY_SLIP": {
            "name": "Giving the Slip",
            "description": "Use your wiles (or your abrasive personality) to slip away from Duke and join Stella instead.",
            "chapter": "1",
            "image": "achievement_icons\ACH_MONDAY_SLIP.png",
            "image_gray": "achievement_icons\ACH_MONDAY_SLIP_gray.png",
        },
        "ACH_MONDAY_HOT_SAVE": {
            "name": "Beautiful People Don't Do Ugly Things",
            "description": "Have your beauty save you from making a disastrous first impression in front of a *small* audience.",
            "chapter": "1",
            "image": "achievement_icons\ACH_MONDAY_HOT_SAVE.png",
            "image_gray": "achievement_icons\ACH_MONDAY_HOT_SAVE_gray.png",
        },
        "ACH_MONDAY_VOICEMAIL": {
            "name": "Straight to Voicemail",
            "description": "Wilfully ignore a phone call while hiking in the woods.",
            "chapter": "1",
            "image": "achievement_icons\ACH_MONDAY_VOICEMAIL.png",
            "image_gray": "achievement_icons\ACH_MONDAY_VOICEMAIL_gray.png",
        },
        "ACH_STELLA_PATH": {
            "name": "A Path in the Woods",
            "description": "Go on an adventure with your new friend",
            "chapter": "1",
            "image": "achievement_icons\ACH_STELLA_PATH.png",
            "image_gray": "achievement_icons\ACH_STELLA_PATH_gray.png",
        },
        "ACH_READING": {
            "name": "Reading Adventure",
            "description": "Spend some time in the library on Tuesday.",
            "chapter": "2",
            "image": "achievement_icons\ACH_READING.png",
            "image_gray": "achievement_icons\ACH_READING_gray.png",
        },
        "ACH_KANEEKA_YOU": {
            "name": "Y—you!",
            "description": "You didn't think your actions would have consequences, did you?",
            "chapter": "1",
            "image": "achievement_icons\ACH_KANEEKA_YOU.png",
            "image_gray": "achievement_icons\ACH_KANEEKA_YOU_gray.png",
        },
        "ACH_TUESDAY_ESTATE": {
            "name": "Refusing the Call",
            "description": "The most fun move is not to play.",
            "chapter": "2",
            "image": "achievement_icons\ACH_TUESDAY_ESTATE.png",
            "image_gray": "achievement_icons\ACH_TUESDAY_ESTATE_gray.png",
        },
        "ACH_TUESDAY_MAP": {
            "name": "Shadowing the Boss",
            "description": "Bother your cousin at work on Tuesday without anyone taking you to her.",
            "chapter": "2",
            "image": "achievement_icons\ACH_TUESDAY_MAP.png",
            "image_gray": "achievement_icons\ACH_TUESDAY_MAP_gray.png",
        },
        "ACH_CHAMBERS": {
            "name": "Her Ladyship's Chambers",
            "description": "Explore Edwardine's bedroom",
            "chapter": "5",
            "image": "achievement_icons\ACH_CHAMBERS.png",
            "image_gray": "achievement_icons\ACH_CHAMBERS_gray.png",
        },
        "ACH_ANGEL": {
            "name": "Angel of Music",
            "description": "Answer his call",
            "chapter": "5",
            "image": "achievement_icons\ACH_ANGEL.png",
            "image_gray": "achievement_icons\ACH_ANGEL_gray.png",
        },
        "ACH_CHEATER": {
            "name": "I Shouldn't...",
            "description": "Succumb to his seduction while committed to another.",
            "chapter": "5",
            "image": "achievement_icons\ACH_CHEATER.png",
            "image_gray": "achievement_icons\ACH_CHEATER_gray.png",
        },
        "ACH_YURI": {
            "name": "Toxic Yuri",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_YURI.png",
            "image_gray": "achievement_icons\ACH_YURI_gray.png",
        },
        "ACH_GREATER_GOOD": {
            "name": "For the Greater Good",
            "description": "Successfully sacrifice yourself for the good of the town.",
            "chapter": "5",
            "image": "achievement_icons\ACH_GREATER_GOOD.png",
            "image_gray": "achievement_icons\ACH_GREATER_GOOD_gray.png",
        },
        "ACH_DOCTOR_HELP": {
            "name": "Walk-in Clinic",
            "description": "Turn to the Doctor in your hour of need.",
            "chapter": "5",
            "image": "achievement_icons\ACH_DOCTOR_HELP.png",
            "image_gray": "achievement_icons\ACH_DOCTOR_HELP_gray.png",
        },
        "ACH_WALL": {
            "name": "Breaking Point",
            "description": "Make your cousin cry.",
            "chapter": "5",
            "image": "achievement_icons\ACH_WALL.png",
            "image_gray": "achievement_icons\ACH_WALL_gray.png",
        },
        "ACH_IMPASSE_5": {
            "name": "Worlds Apart",
            "description": "Reach an impasse with your cousin",
            "chapter": "5",
            "image": "achievement_icons\ACH_IMPASSE_5.png",
            "image_gray": "achievement_icons\ACH_IMPASSE_5_gray.png",
        },
        "ACH_TABITHA_FIGHT_5": {
            "name": "Don't Move",
            "description": "Push your cousin to the brink",
            "chapter": "5",
            "image": "achievement_icons\ACH_TABITHA_FIGHT_5.png",
            "image_gray": "achievement_icons\ACH_TABITHA_FIGHT_5_gray.png",
        },
        "ACH_TABITHA_STELLAMANCE_TRUCE": {
            "name": "Back to How Things Were Last Night.",
            "description": "Reach an uneasy truce after romancing your cousin's ex",
            "chapter": "5",
            "image": "achievement_icons\ACH_TABITHA_STELLAMANCE_TRUCE.png",
            "image_gray": "achievement_icons\ACH_TABITHA_STELLAMANCE_TRUCE_gray.png",
        },
        "ACH_REDACTED_5": {
            "name": "There was never a ??? in Scarlet Hollow",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_REDACTED_5.png",
            "image_gray": "achievement_icons\ACH_REDACTED_5_gray.png",
        },
        "ACH_OSCAR_BYE": {
            "name": "The End of the Road",
            "description": "Say goodbye to Oscar in Episode 5",
            "chapter": "5",
            "image": "achievement_icons\ACH_OSCAR_BYE.png",
            "image_gray": "achievement_icons\ACH_OSCAR_BYE_gray.png",
        },
        "ACH_OSCAR_SANITY": {
            "name": "Roll for Sanity",
            "description": "Speak with Oscar after he's made contact with something... Other",
            "chapter": "5",
            "image": "achievement_icons\ACH_OSCAR_SANITY.png",
            "image_gray": "achievement_icons\ACH_OSCAR_SANITY_gray.png",
        },
        "ACH_OSCAR_FLOOR": {
            "name": "The Floorplans are All Wrong",
            "description": "Speak with Oscar after his research has turned up an important discovery.",
            "chapter": "5",
            "image": "achievement_icons\ACH_OSCAR_FLOOR.png",
            "image_gray": "achievement_icons\ACH_OSCAR_FLOOR_gray.png",
        },
        "ACH_OSCAR_DETERMINED": {
            "name": "Determination at Last",
            "description": "Speak with Oscar after he's chosen a dangerous course of action.",
            "chapter": "5",
            "image": "achievement_icons\ACH_OSCAR_DETERMINED.png",
            "image_gray": "achievement_icons\ACH_OSCAR_DETERMINED_gray.png",
        },
        "ACH_EGG": {
            "name": "Egg",
            "description": "It's growing inside you.",
            "chapter": "5",
            "image": "achievement_icons\ACH_EGG.png",
            "image_gray": "achievement_icons\ACH_EGG_gray.png",
        },
        "ACH_RIOT_START": {
            "name": "United We Stand",
            "description": "Start a riot",
            "chapter": "5",
            "image": "achievement_icons\ACH_RIOT_START.png",
            "image_gray": "achievement_icons\ACH_RIOT_START_gray.png",
        },
        "ACH_OWL_PELLET": {
            "name": "Pellet",
            "description": "What happened to the bones?",
            "chapter": "5",
            "image": "achievement_icons\ACH_OWL_PELLET.png",
            "image_gray": "achievement_icons\ACH_OWL_PELLET_gray.png",
        },
        "ACH_COPS_HELP": {
            "name": "The Police are Here to Help!",
            "description": "Go to the cops in your hour of need",
            "chapter": "5",
            "image": "achievement_icons\ACH_COPS_HELP.png",
            "image_gray": "achievement_icons\ACH_COPS_HELP_gray.png",
        },
        "ACH_AVERY_HELP": {
            "name": "One stop, then we're out of here!",
            "description": "Hitch a ride with Avery",
            "chapter": "5",
            "image": "achievement_icons\ACH_AVERY_HELP.png",
            "image_gray": "achievement_icons\ACH_AVERY_HELP_gray.png",
        },
        "ACH_WINNIE_HELP": {
            "name": "Missed Connection",
            "description": "Chat with Winnie in Episode 5",
            "chapter": "5",
            "image": "achievement_icons\ACH_WINNIE_HELP.png",
            "image_gray": "achievement_icons\ACH_WINNIE_HELP_gray.png",
        },
        "ACH_STELLA_HELP": {
            "name": "Back to Basics",
            "description": "Turn to a YouTuber in your hour of need.",
            "chapter": "5",
            "image": "achievement_icons\ACH_STELLA_HELP.png",
            "image_gray": "achievement_icons\ACH_STELLA_HELP_gray.png",
        },
        "ACH_REESE_HELP": {
            "name": "The Calling",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_REESE_HELP.png",
            "image_gray": "achievement_icons\ACH_REESE_HELP_gray.png",
        },
        "ACH_WAYNE_ROMANCE_5": {
            "name": "Ecstasy",
            "description": "Share a moment of bliss with your guardian angel.",
            "chapter": "5",
            "image": "achievement_icons\ACH_WAYNE_ROMANCE_5.png",
            "image_gray": "achievement_icons\ACH_WAYNE_ROMANCE_5_gray.png",
        },
        "ACH_WANTED": {
            "name": "Six Star Wanted Level",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_WANTED.png",
            "image_gray": "achievement_icons\ACH_WANTED_gray.png",
        },
        "ACH_REESE_ASSASSIN": {
            "name": "I'll do what's best for you...",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_REESE_ASSASSIN.png",
            "image_gray": "achievement_icons\ACH_REESE_ASSASSIN_gray.png",
        },
        "ACH_PB5": {
            "name": "Mx Universe",
            "description": "Finish Episode 5 with Powerful Build",
            "chapter": "5",
            "image": "achievement_icons\ACH_PB5.png",
            "image_gray": "achievement_icons\ACH_PB5_gray.png",
        },
        "ACH_HARDCORE5": {
            "name": "No no no no no",
            "description": "Finish Episode 5 in Hardcore Mode",
            "chapter": "5",
            "image": "achievement_icons\ACH_HARDCORE5.png",
            "image_gray": "achievement_icons\ACH_HARDCORE5_gray.png",
        },
        "ACH_KEEN5": {
            "name": "Shinigami Hunter",
            "description": "Finish Episode 5 with Keen Eye",
            "chapter": "5",
            "image": "achievement_icons\ACH_KEEN5.png",
            "image_gray": "achievement_icons\ACH_KEEN5_gray.png",
        },
        "ACH_BOOK5": {
            "name": "The Picture of Dorian Gray",
            "description": "Finish Episode 5 with Book Smart",
            "chapter": "5",
            "image": "achievement_icons\ACH_BOOK5.png",
            "image_gray": "achievement_icons\ACH_BOOK5_gray.png",
        },
        "ACH_STREET5": {
            "name": "Bridge Salesman",
            "description": "Finish Episode 5 with Street Smart",
            "chapter": "5",
            "image": "achievement_icons\ACH_STREET5.png",
            "image_gray": "achievement_icons\ACH_STREET5_gray.png",
        },
        "ACH_MYST5": {
            "name": "I AM JUSTICE!",
            "description": "Finish Episode 5 with Mystical",
            "chapter": "5",
            "image": "achievement_icons\ACH_MYST5.png",
            "image_gray": "achievement_icons\ACH_MYST5_gray.png",
        },
        "ACH_TTA5": {
            "name": "The Power of Heart!",
            "description": "Finish Episode 5 with Talk to Animals",
            "chapter": "5",
            "image": "achievement_icons\ACH_TTA5.png",
            "image_gray": "achievement_icons\ACH_TTA5_gray.png",
        },
        "ACH_HOT5": {
            "name": "Habanero",
            "description": "Finish Episode 5 with Hot",
            "chapter": "5",
            "image": "achievement_icons\ACH_HOT5.png",
            "image_gray": "achievement_icons\ACH_HOT5_gray.png",
        },
        "ACH_TABBY_YOUNG": {
            "name": "Do It For Her",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_TABBY_YOUNG.png",
            "image_gray": "achievement_icons\ACH_TABBY_YOUNG_gray.png",
        },
        "ACH_HISTORY_FLUNK": {
            "name": "You can't re-write history, even if you'd like to",
            "description": "Make every incorrect choice while retreading the past.",
            "chapter": "5",
            "image": "achievement_icons\ACH_HISTORY_FLUNK.png",
            "image_gray": "achievement_icons\ACH_HISTORY_FLUNK_gray.png",
        },
        "ACH_HISTORY_ACE": {
            "name": "A World Without You There to Guide It...",
            "description": "Make no incorrect choices while retreading the past.",
            "chapter": "5",
            "image": "achievement_icons\ACH_HISTORY_ACE.png",
            "image_gray": "achievement_icons\ACH_HISTORY_ACE_gray.png",
        },
        "ACH_RESPONSIBILITY": {
            "name": "I've been there with you every night you've been alive",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_RESPONSIBILITY.png",
            "image_gray": "achievement_icons\ACH_RESPONSIBILITY_gray.png",
        },
        "ACH_SHOOT_OUT": {
            "name": "Il buono, il brutto, il cattivo",
            "description": "Survive a standoff after multiple shots have been fired.",
            "chapter": "5",
            "image": "achievement_icons\ACH_SHOOT_OUT.png",
            "image_gray": "achievement_icons\ACH_SHOOT_OUT_gray.png",
        },
        "ACH_BABY_CLOCK": {
            "name": "Inaction is still a choice",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_BABY_CLOCK.png",
            "image_gray": "achievement_icons\ACH_BABY_CLOCK_gray.png",
        },
        "ACH_KEEN_DOUBLE_SAVE": {
            "name": "Shared Burdens",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_KEEN_DOUBLE_SAVE.png",
            "image_gray": "achievement_icons\ACH_KEEN_DOUBLE_SAVE_gray.png",
        },
        "ACH_ANTI_AGE": {
            "name": "Anti-Aging Solution",
            "description": "Regain your lost years.",
            "chapter": "5",
            "image": "achievement_icons\ACH_ANTI_AGE.png",
            "image_gray": "achievement_icons\ACH_ANTI_AGE_gray.png",
        },
        "ACH_SHOT_END": {
            "name": "It was loaded",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_SHOT_END.png",
            "image_gray": "achievement_icons\ACH_SHOT_END_gray.png",
        },
        "ACH_ADOPTION": {
            "name": "It's a Boy!",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_ADOPTION.png",
            "image_gray": "achievement_icons\ACH_ADOPTION_gray.png",
        },
        "ACH_WITCH": {
            "name": "The Witch",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_WITCH.png",
            "image_gray": "achievement_icons\ACH_WITCH_gray.png",
        },
        "ACH_GINSENG": {
            "name": "Ginseng Baby",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_GINSENG.png",
            "image_gray": "achievement_icons\ACH_GINSENG_gray.png",
        },
        "ACH_STELLA_STILL_MISSING": {
            "name": "I Feel Like We're Forgetting Someone",
            "description": "Finish Episodes 4 and 5 Without Seeing Stella",
            "chapter": "5",
            "image": "achievement_icons\ACH_STELLA_STILL_MISSING.png",
            "image_gray": "achievement_icons\ACH_STELLA_STILL_MISSING_gray.png",
        },
        "ACH_COPS_DEAD": {
            "name": "Send more cops...",
            "description": "Scarlet Hollow's finest are no more.",
            "chapter": "5",
            "image": "achievement_icons\ACH_COPS_DEAD.png",
            "image_gray": "achievement_icons\ACH_COPS_DEAD_gray.png",
        },
        "ACH_COPS_SURVIVE": {
            "name": "The Boys in Blue",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_COPS_SURVIVE.png",
            "image_gray": "achievement_icons\ACH_COPS_SURVIVE_gray.png",
        },
        "ACH_WAYNE_ISAACS_VESSEL": {
            "name": "Reunited",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_WAYNE_ISAACS_VESSEL.png",
            "image_gray": "achievement_icons\ACH_WAYNE_ISAACS_VESSEL_gray.png",
        },
        "ACH_BABY_DESTROYED_PLAYER": {
            "name": "A Mockery of Life",
            "description": "Destroy something horrible before it can be born.",
            "chapter": "5",
            "image": "achievement_icons\ACH_BABY_DESTROYED_PLAYER.png",
            "image_gray": "achievement_icons\ACH_BABY_DESTROYED_PLAYER_gray.png",
        },
        "ACH_ILLUSION_5": {
            "name": "The Illusion of Choice II",
            "description": "Have a choice taken away from you in bounty's den.",
            "chapter": "5",
            "image": "achievement_icons\ACH_ILLUSION_5.png",
            "image_gray": "achievement_icons\ACH_ILLUSION_5_gray.png",
        },
        "ACH_COUSIN_BOND_KANEEKA": {
            "name": "Cousinly Bonds",
            "description": "A Scarlet stops another from saving someone forgotten.",
            "chapter": "5",
            "image": "achievement_icons\ACH_COUSIN_BOND_KANEEKA.png",
            "image_gray": "achievement_icons\ACH_COUSIN_BOND_KANEEKA_gray.png",
        },
        "ACH_AVERY_DIES": {
            "name": "Nobody left to do better than this...",
            "description": "Lose the barista",
            "chapter": "5",
            "image": "achievement_icons\ACH_AVERY_DIES.png",
            "image_gray": "achievement_icons\ACH_AVERY_DIES_gray.png",
        },
        "ACH_AVERY_LIVES": {
            "name": "A Second Chance at Life",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_AVERY_LIVES.png",
            "image_gray": "achievement_icons\ACH_AVERY_LIVES_gray.png",
        },
        "ACH_KANEEKA_SACRIFICE_REMEMBER": {
            "name": "The Burden of Memory",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_KANEEKA_SACRIFICE_REMEMBER.png",
            "image_gray": "achievement_icons\ACH_KANEEKA_SACRIFICE_REMEMBER_gray.png",
        },
        "ACH_CHARACTER_FORGOTTEN": {
            "name": "Missing Achievement Data",
            "description": "Forget somebody forever.",
            "chapter": "5",
            "image": "achievement_icons\ACH_CHARACTER_FORGOTTEN.png",
            "image_gray": "achievement_icons\ACH_CHARACTER_FORGOTTEN_gray.png",
        },
        "ACH_CARMILLAMANCE_FORGET": {
            "name": "Retcon",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_CARMILLAMANCE_FORGET.png",
            "image_gray": "achievement_icons\ACH_CARMILLAMANCE_FORGET_gray.png",
        },
        "ACH_CARMILLAMANCE_REMEMBER": {
            "name": "Problematic Age Gap",
            "description": "Romance someone you know is much older than you.",
            "chapter": "5",
            "image": "achievement_icons\ACH_CARMILLAMANCE_REMEMBER.png",
            "image_gray": "achievement_icons\ACH_CARMILLAMANCE_REMEMBER_gray.png",
        },
        "ACH_FAUSTIAN_BARGAIN": {
            "name": "Faustian Bargain",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_FAUSTIAN_BARGAIN.png",
            "image_gray": "achievement_icons\ACH_FAUSTIAN_BARGAIN_gray.png",
        },
        "ACH_HUNGRY_BOY": {
            "name": "Once is happenstance, twice is a coincidence...",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_HUNGRY_BOY.png",
            "image_gray": "achievement_icons\ACH_HUNGRY_BOY_gray.png",
        },
        "ACH_LAMB": {
            "name": "On the Lamb",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_LAMB.png",
            "image_gray": "achievement_icons\ACH_LAMB_gray.png",
        },
        "ACH_LAWFUL": {
            "name": "Law Abiding-Citizen",
            "description": "Make it to the farms without ever being on the police's radar.",
            "chapter": "5",
            "image": "achievement_icons\ACH_LAWFUL.png",
            "image_gray": "achievement_icons\ACH_LAWFUL_gray.png",
        },
        "ACH_ROMANCE_KANEEKA_SACRIFICE": {
            "name": "She Will Make for a Sacrificial Heart",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_ROMANCE_KANEEKA_SACRIFICE.png",
            "image_gray": "achievement_icons\ACH_ROMANCE_KANEEKA_SACRIFICE_gray.png",
        },
        "ACH_KANEEKA_MYSTIC": {
            "name": "The Thread Woven Backwards",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_KANEEKA_MYSTIC.png",
            "image_gray": "achievement_icons\ACH_KANEEKA_MYSTIC_gray.png",
        },
        "ACH_KANEEKA_FAIL": {
            "name": "Slipping Through Your Words",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_KANEEKA_FAIL.png",
            "image_gray": "achievement_icons\ACH_KANEEKA_FAIL_gray.png",
        },
        "ACH_PROMISEDLAND": {
            "name": "If I could take one moment into my hands",
            "description": "",
            "chapter": "5",
            "image": "achievement_icons\ACH_PROMISEDLAND.png",
            "image_gray": "achievement_icons\ACH_PROMISEDLAND_gray.png",
        },
    }

