init -1 python in mod_achievement_override:
    ## from https://steamdb.info/app/1609230/stats/
    ## surely there's a better way to do translation, but idc
    
    ##for (var a of $0.children) {
    ##   const parent = a.firstElementChild.nextElementSibling.firstElementChild.nextElementSibling.firstElementChild
    ##    temp.push('"' + a.id.substring("achievement-".length).toLowerCase() + '": "' + parent.firstElementChild.innerHTML + '"')
    ##}
    ##console.log(temp.sort().join(",\n        "))
    
    name_map = {
        "ach_adoption": "It's a Boy!",
        "ach_angel": "Angel of Music",
        "ach_anti_age": "Anti-Aging Solution",
        "ach_artist": "The Artist",
        "ach_asmr": "Antagonistic Doctor Roleplay (ASMR)",
        "ach_avery_dies": "Nobody left to do better than this...",
        "ach_avery_help": "One stop, then we're out of here!",
        "ach_avery_lives": "A Second Chance at Life",
        "ach_baby_clock": "Inaction is still a choice",
        "ach_baby_destroyed_player": "A Mockery of Life",
        "ach_babysitter": "Pro Babysitter",
        "ach_basement4": "The Excavation of Oscar's Basement",
        "ach_beastmaster": "Tame the Beast",
        "ach_book1": "The Ravenous Bug",
        "ach_book2": "Whimsical Tree Adventure",
        "ach_book3": "A Supernatural Love Affair",
        "ach_book4": "Of Mice and Men",
        "ach_book5": "The Picture of Dorian Gray",
        "ach_boomer": "Father, how do I click the book?",
        "ach_boycry": "The Boy Who Cried Nice House",
        "ach_browsing": "Just Browsing",
        "ach_carmillamance_forget": "Retcon",
        "ach_carmillamance_remember": "Problematic Age Gap",
        "ach_chambers": "Her Ladyship's Chambers",
        "ach_character_forgotten": "Missing Achievement Data",
        "ach_cheater": "I Shouldn't...",
        "ach_church4": "The Smallest Church in Scarlet Hollow",
        "ach_coffee": "Coffee Date",
        "ach_combo": "Fusion",
        "ach_confidant": "Confidant",
        "ach_cops_dead": "Send more cops...",
        "ach_cops_help": "The Police are Here to Help!",
        "ach_cops_survive": "The Boys in Blue",
        "ach_courtesycall": "Courtesy Call",
        "ach_cousin_bond_kaneeka": "Cousinly Bonds",
        "ach_cuttingloss": "Cutting Your Losses",
        "ach_diner4": "What's the Buzz?",
        "ach_dirty": "Unclean",
        "ach_ditchling": "Ditchling",
        "ach_doctor_help": "Walk-in Clinic",
        "ach_dril": "I’m not owned! I’m not owned!",
        "ach_dukerip": "Poor Trigger Discipline",
        "ach_dustinbetray": "Friendship Ended with Dresser Rat",
        "ach_eagles": "New Kid in Town",
        "ach_egg": "Egg",
        "ach_estate1": "Good Cousin",
        "ach_eviltriumph": "Evil Has Triumphed",
        "ach_expectations": "What were you expecting?",
        "ach_faustian_bargain": "Faustian Bargain",
        "ach_femalegaze": "I'm Looking Respectfully.",
        "ach_flight": "Cat and Mouse",
        "ach_fred": "Let's See Who This Really Is",
        "ach_getout": "Get Out of My Head!",
        "ach_ghostmax": "The Gang's All Here",
        "ach_ghostmin": "Tight-Knit Social Circle",
        "ach_ginseng": "Ginseng Baby",
        "ach_goat": "Dustin Quest",
        "ach_goku": "Imma deck you in the schnoz!",
        "ach_greater_good": "For the Greater Good",
        "ach_gretchenregards": "Gretchen Sends Her Regards",
        "ach_gumshoe": "Mr X.",
        "ach_hacker": "Hackerman",
        "ach_hardcore1": "No",
        "ach_hardcore2": "No no",
        "ach_hardcore3": "No no no",
        "ach_hardcore4": "No no no no",
        "ach_hardcore5": "No no no no no",
        "ach_harrisonstop": "Saving the Family Business",
        "ach_history_ace": "A World Without You There to Guide It...",
        "ach_history_flunk": "You can't re-write history, even if you'd like to",
        "ach_hospitality": "Southern Hospitality",
        "ach_hot1": "Bell Pepper",
        "ach_hot2": "Poblano",
        "ach_hot3": "Jalapeño",
        "ach_hot4": "Cayenne",
        "ach_hot5": "Habanero",
        "ach_hotmonster": "Monster Lover",
        "ach_hungry_boy": "Once is happenstance, twice is a coincindence...",
        "ach_hygge": "Hygge",
        "ach_ice_cream": "Ice Cream Social",
        "ach_illusion": "The Illusion of Choice",
        "ach_illusion_5": "The Illusion of Choice II",
        "ach_impasse_5": "Worlds Apart",
        "ach_justus": "Just the Two of Us",
        "ach_kaioken": "TIMES THREE!",
        "ach_kaneeka_fail": "Slipping Through Your Words",
        "ach_kaneeka_mystic": "The Thread Woven Backwards",
        "ach_kaneeka_sacrifice_remember": "The Burden of Memory",
        "ach_kaneeka_you": "Y—you!",
        "ach_kaneekamance": "You can't start a fire...",
        "ach_keen1": "Mail Time",
        "ach_keen2": "French Inspector",
        "ach_keen3": "Detective Arriving on the Scene",
        "ach_keen4": "Louisiana Hunch",
        "ach_keen5": "Shinigami Hunter",
        "ach_keen_double_save": "Shared Burdens",
        "ach_keepsecret": "Alright Then, Keep Your Secrets",
        "ach_kington": "Master Codebreaker",
        "ach_lamb": "On the Lamb",
        "ach_lawful": "Law Abiding-Citizen",
        "ach_library4": "Library Card",
        "ach_lifeline": "Lifeline",
        "ach_lion": "I (Don't) Want to Believe",
        "ach_loremaster": "Loremaster",
        "ach_losdos": "Porqué no los Dos?",
        "ach_manager": "I Want to Talk to Your Manager",
        "ach_matricide": "Matricide",
        "ach_maxwell4": "At Least It's (Probably) Not Haunted",
        "ach_mines": "Picket Line",
        "ach_minion": "Minion",
        "ach_monday_duke": "Cracking Open a Cold One",
        "ach_monday_hot_save": "Beautiful People Don't Do Ugly Things",
        "ach_monday_library": "History Lesson",
        "ach_monday_slip": "Giving the Slip",
        "ach_monday_store": "Scarlet Hollow",
        "ach_monday_voicemail": "Straight to Voicemail",
        "ach_mouseketeer": "Members Only",
        "ach_myst1": "Enoby Dark'ness Dementia Raven Way",
        "ach_myst2": "Sand-Hater",
        "ach_myst3": "Card Master",
        "ach_myst4": "Wish Maker",
        "ach_myst5": "I AM JUSTICE!",
        "ach_nofriends": "I Didn't Come Here to Make Friends",
        "ach_nomanleft": "No Man Left Behind",
        "ach_nosynancy": "Nosy Nancy",
        "ach_obedient": "Obedient",
        "ach_oops": "Ya blew it",
        "ach_ootl": "Out of the Loop",
        "ach_oscar_bye": "The End of the Road",
        "ach_oscar_determined": "Determination at Last",
        "ach_oscar_floor": "The Floorplans are All Wrong",
        "ach_oscar_sanity": "Roll for Sanity",
        "ach_oscarmance": "Dream Daddy",
        "ach_owl_pellet": "Pellet",
        "ach_pac": "Generous Campaign Contribution",
        "ach_patzero": "Patient Zero",
        "ach_pb1": "Mx North Carolina",
        "ach_pb2": "Mx America",
        "ach_pb3": "Mx World",
        "ach_pb4": "Mx Galaxy",
        "ach_pb5": "Mx Universe",
        "ach_pbj": "Cooking by the book.",
        "ach_petdog": "Can You Pet the Dog?",
        "ach_phantom": "Prying Pandora",
        "ach_phoenix": "The Haunted Turnabout",
        "ach_pinkerton": "Pinkerton",
        "ach_playfield": "Playing the Field",
        "ach_police4": "Why Won't They Just Do Their Jobs?",
        "ach_poltergeist": "This House is Clean",
        "ach_problematicfav": "I can fix her!",
        "ach_promisedland": "If I could take one moment into my hands",
        "ach_reading": "Reading Adventure",
        "ach_redacted_5": "There was never a ??? in Scarlet Hollow",
        "ach_reese_assassin": "I'll do what's best for you...",
        "ach_reese_dead": "Cousin Bonding Time",
        "ach_reese_help": "The Calling",
        "ach_reesemance": "Monster Lover II",
        "ach_resonant": "Resonant",
        "ach_responsibility": "I've been there with you every night you've been alive",
        "ach_ridekaneeka": "Mystery Machine",
        "ach_riot_start": "United We Stand",
        "ach_ripgretch": "Old Yeller",
        "ach_river": "Family Burdens",
        "ach_romance": "This is a Dating Sim, Right?",
        "ach_romance_kaneeka_sacrifice": "She Will Make for a Sacrificial Heart",
        "ach_seance": "Seance",
        "ach_shoot_out": "Il buono, il brutto, il cattivo",
        "ach_shot_end": "It was loaded",
        "ach_shower": "Wash away your sins",
        "ach_sins": "The Sins of the Father...",
        "ach_sinsbreak": "Shall Not Be Visited Upon the Son",
        "ach_sinsdeal": "Are To Be Laid Upon the Children",
        "ach_slumber": "Slumber Party!",
        "ach_smile": "That Damned Smile.",
        "ach_snitch": "Ronnie the Rat",
        "ach_snitchsnitch": "Rodriguez the Rat",
        "ach_squelch": "Squelch",
        "ach_status_quo": "Keeping the status quo",
        "ach_stealthrun": "Stealth Run",
        "ach_stella_found": "At the Edge of Everything...",
        "ach_stella_gone": "Where in the World is Stella Richmond?",
        "ach_stella_help": "Back to Basics",
        "ach_stella_path": "A Path in the Woods",
        "ach_stella_still_missing": "I Feel Like We're Forgetting Someone",
        "ach_stella_tabitha": "I Never Forgot About You",
        "ach_stellamance": "Tear Down the Wall",
        "ach_stickbug": "Get Stick Bugged",
        "ach_stickyfingers": "Sticky Fingers",
        "ach_still": "Still Life",
        "ach_street1": "Candy From a Baby",
        "ach_street2": "Stealing Your Grandma's Credit Card",
        "ach_street3": "This is a Stick-Up!",
        "ach_street4": "Good ol' Fashion Train Robbery",
        "ach_street5": "Bridge Salesman",
        "ach_tabby_young": "Do It For Her",
        "ach_tabitha_fight_5": "Don't Move",
        "ach_tabitha_stellamance_truce": "Back to How Things Were Last Night.",
        "ach_tea": "Tea Reading",
        "ach_teaspill": "Spill the Tea",
        "ach_thunderroad": "Thunder Road.",
        "ach_tommyknocker": "Tommyknocker",
        "ach_tta1": "Pasta Puppeteer",
        "ach_tta2": "Jane Goodall",
        "ach_tta3": "Teen Talker",
        "ach_tta4": "Creature Consolation",
        "ach_tta5": "The Power of Heart!",
        "ach_tuesday_estate": "Refusing the Call",
        "ach_tuesday_map": "Shadowing the Boss",
        "ach_turn": "Not an Ambi-Turner.",
        "ach_urban": "Urban Explorer",
        "ach_walkstella": "Into the Woods... Again",
        "ach_wall": "Breaking Point",
        "ach_wanted": "Six Star Wanted Level",
        "ach_wayne_isaacs_vessel": "Reunited",
        "ach_wayne_romance_5": "Ecstasy",
        "ach_whoami": "Time to Whip Out the Old String and Corkboard",
        "ach_winnie_help": "Missed Connection",
        "ach_witch": "The Witch",
        "ach_yuri": "Toxic Yuri"
    }